require 'rake/clean'

CLEAN.include '*.o', 'Makefile', 'mkmf.log'
CLOBBER.include 'taglib.so'

task 'default' => [:swig, 'Makefile'] do
  sh "make"
end

task :swig => ['taglib_wrap.cxx', 'taglib_mpeg_wrap.cxx']

file 'taglib_wrap.cxx' => ['taglib.i'] do
  sh "swig -c++ -ruby -initname taglib -I/usr/include taglib.i"
end

file 'taglib_mpeg_wrap.cxx' => ['taglib_mpeg.i'] do
  sh "swig -c++ -ruby -initname taglib -I/usr/include taglib_mpeg.i"
end

file 'Makefile' => ['extconf.rb'] do
  ruby "extconf.rb"
end

