AllCops:
  NewCops: disable
  Include:
    - '**/*.rb'
    - '**/*.arb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/.simplecov'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'docs/**/*'
    - 'tmp/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
