require 'rake/clean'

CLEAN.include 'taglib_*/*.o', 'taglib_*/Makefile', 'taglib_*/mkmf.log'
CLOBBER.include 'taglib_*/*.so'

modules = ["taglib_base", "taglib_mpeg", "taglib_id3v2"]

swig = `which swig2.0`
if swig.empty?
  swig = `which swig`
end
swig.chomp!

task 'default' => [:swig, :make]

task :swig do
  modules.each do |mod|
    sh "cd #{mod} && #{swig} -c++ -ruby -autorename -initname #{mod} -I/usr/include #{mod}.i"
  end
end

task :extconf do
  modules.each do |mod|
    sh "cd #{mod} && ruby extconf.rb"
  end
end

task :make => [:extconf] do
  modules.each do |mod|
    sh "cd #{mod} && make"
  end
end
